name: webstore
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter
  go_router: ^14.6.2
  provider: ^6.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/Images/
    - assets/Images/skincare1.png 
    - assets/Images/skencare2.png 
    - assets/Images/skencare3.png 
    - assets/Images/skencare4.png 
    - assets/Images/skincare5.png 
    - assets/Images/skincare6.png 
    - assets/Images/skincare7.png 
    - assets/Images/skencare8.png